/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gym.glb 
Author: Brynn (https://sketchfab.com/Brynnnnn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-isometric-rooms-d53af0ad289a403598ee2cb41d84608b
Title: Low Poly Isometric Rooms
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/gym.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.15, 0.01, 0.15]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.01}>
            <group position={[0, 275, 365]}>
              <group rotation={[0, Math.PI / 2, 0]}>
                <mesh
                  geometry={nodes.Wood_Plank1_Colors_0.geometry}
                  material={materials.Colors}
                  position={[0, 2.5, 100]}
                />
                <mesh
                  geometry={nodes.Wood_Plank2_Colors_0.geometry}
                  material={materials.Colors}
                  position={[0, 2.5, 50]}
                />
                <mesh
                  geometry={nodes.Wood_Plank3_Colors_0.geometry}
                  material={materials.Colors}
                  position={[0, 2.5, 0]}
                />
                <mesh
                  geometry={nodes.Wood_Plank4_Colors_0.geometry}
                  material={materials.Colors}
                  position={[0, 2.5, -50]}
                />
                <mesh
                  geometry={nodes.Wood_Plank5_Colors_0.geometry}
                  material={materials.Colors}
                  position={[0, 2.5, -100]}
                />
                <mesh
                  geometry={nodes.Wood_Plank6_Colors_0.geometry}
                  material={materials.Colors}
                  position={[0, 2.5, -150]}
                />
                <mesh
                  geometry={nodes.Wood_Plank7_Colors_0.geometry}
                  material={materials.Colors}
                  position={[0, 2.5, 150]}
                />
              </group>
              <group position={[-21.788, 0, 16.031]} rotation={[0, -0.272, 0]}>
                <mesh
                  geometry={nodes.Leg14_Colors_0.geometry}
                  material={materials.Colors}
                  position={[350, -269.5, -65.172]}
                />
                <mesh
                  geometry={nodes.Leg15_Colors_0.geometry}
                  material={materials.Colors}
                  position={[350, -269.5, -65.172]}
                />
                <mesh
                  geometry={nodes.Top2_Colors_0.geometry}
                  material={materials.Colors}
                  position={[52.272, -17.5, -16.008]}
                  scale={[0.6, 1, 0.35]}
                />
              </group>
              <mesh
                geometry={nodes.Walls2_Colors_0.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.Telescope_Colors_0.geometry}
                material={materials.Colors}
                position={[-5.005, 5, 162.68]}
              />
              <mesh
                geometry={nodes.Bed_Colors_0.geometry}
                material={materials.Colors}
                position={[65, 5, 99.73]}
                rotation={[-Math.PI, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Shelf1_Colors_0.geometry}
                material={materials.Colors}
                position={[-155, 200, -44.126]}
              />
              <mesh
                geometry={nodes.Shelf2_Colors_0.geometry}
                material={materials.Colors}
                position={[-155, 155, 50]}
              />
              <mesh
                geometry={nodes.Book5_Colors_0.geometry}
                material={materials.Colors}
                position={[-154.5, 174.811, 30.12]}
                rotation={[-Math.PI / 10, 0, 0]}
              />
              <mesh
                geometry={nodes.Book4_Colors_0.geometry}
                material={materials.Colors}
                position={[-154.977, 164, 88.807]}
                rotation={[-Math.PI / 2, 0, 0.182]}
              />
              <mesh
                geometry={nodes.Book3_Colors_0.geometry}
                material={materials.Colors}
                position={[-152.259, 174, 118.487]}
              />
              <mesh
                geometry={nodes.Book2_Colors_0_1.geometry}
                material={materials.Colors}
                position={[-152.259, 174, 15.664]}
              />
              <mesh
                geometry={nodes.Book1_Colors_0_1.geometry}
                material={materials.Colors}
                position={[-152.259, 174, -9.512]}
              />
              <mesh
                geometry={nodes.Book_Colors_0.geometry}
                material={materials.Colors}
                position={[-152.259, 174, -21.217]}
              />
              <mesh
                geometry={nodes.Book6_Colors_0.geometry}
                material={materials.Colors}
                position={[-152.259, 219, -74.428]}
              />
              <mesh
                geometry={nodes.Book7_Colors_0.geometry}
                material={materials.Colors}
                position={[-152.259, 219, 28.395]}
              />
              <mesh
                geometry={nodes.Book8_Colors_0.geometry}
                material={materials.Colors}
                position={[-152.259, 219, 17.271]}
              />
              <mesh
                geometry={nodes.Book9_Colors_0.geometry}
                material={materials.Colors}
                position={[-150.766, 209.022, -14.949]}
                rotation={[-1.57, -0.008, 0.179]}
              />
              <mesh
                geometry={nodes.Book10_Colors_0.geometry}
                material={materials.Colors}
                position={[-154.5, 219, -59.972]}
                rotation={[-Math.PI / 10, 0, 0]}
              />
              <mesh
                geometry={nodes.Book11_Colors_0.geometry}
                material={materials.Colors}
                position={[-150.766, 218.99, -14.949]}
                rotation={[-1.57, -0.008, -0.089]}
              />
              <mesh
                geometry={nodes.Book12_Colors_0.geometry}
                material={materials.Colors}
                position={[-104.351, 76, -133.3]}
                rotation={[-Math.PI / 2, 0, -0.373]}
              />
              <mesh
                geometry={nodes.Book13_Colors_0.geometry}
                material={materials.Colors}
                position={[-104.351, 86, -133.3]}
                rotation={[-Math.PI / 2, 0, -0.025]}
              />
              <mesh
                geometry={nodes.Top_Colors_0.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.Drawer_Colors_0.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.Handle_Colors_0_1.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.Leg1_Colors_0.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.Leg2_Colors_0.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.Leg3_Colors_0.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.Computer_Colors_0.geometry}
                material={materials.Colors}
                position={[-93.596, 20.15, -38.58]}
                rotation={[-Math.PI, 1.484, -Math.PI]}
                scale={0.5}
              />
              <mesh
                geometry={nodes.Keyboard_Colors_0.geometry}
                material={materials.Colors}
                position={[-100.334, 91, -37.961]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[0.5, 0.4, 0.2]}
              />
              <mesh
                geometry={nodes.CPU_Colors_0.geometry}
                material={materials.Colors}
                position={[-145.328, 91, -103.557]}
                scale={[0.5, 0.4, 0.2]}
              />
              <mesh
                geometry={nodes.Mouse_Colors_0.geometry}
                material={materials.Colors}
                position={[-96.751, 91, -82.792]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[0.101, 0.4, 0.151]}
              />
              <mesh
                geometry={nodes.Top_Colors_0_1.geometry}
                material={materials.Colors}
                position={[50, 210, 160]}
              />
              <mesh
                geometry={nodes.String1_Colors_0.geometry}
                material={materials.Colors}
                position={[-20, 153.468, 157.5]}
              />
              <mesh
                geometry={nodes.String2_Colors_0.geometry}
                material={materials.Colors}
                position={[120, 153.468, 157.5]}
              />
              <mesh
                geometry={nodes.Blind1_Colors_0.geometry}
                material={materials.Colors}
                position={[50, 180, 157.5]}
                rotation={[-Math.PI / 3, 0, 0]}
              />
              <mesh
                geometry={nodes.Blind2_Colors_0.geometry}
                material={materials.Colors}
                position={[50, 170, 157.5]}
                rotation={[-Math.PI / 3, 0, 0]}
              />
              <mesh
                geometry={nodes.Blind3_Colors_0.geometry}
                material={materials.Colors}
                position={[50, 160, 157.5]}
                rotation={[-Math.PI / 3, 0, 0]}
              />
              <mesh
                geometry={nodes.Blind4_Colors_0.geometry}
                material={materials.Colors}
                position={[50, 150, 157.5]}
                rotation={[-Math.PI / 3, 0, 0]}
              />
              <mesh
                geometry={nodes.Blind5_Colors_0.geometry}
                material={materials.Colors}
                position={[50, 140, 157.5]}
                rotation={[-Math.PI / 3, 0, 0]}
              />
              <mesh
                geometry={nodes.Blind6_Colors_0.geometry}
                material={materials.Colors}
                position={[50, 130, 157.5]}
                rotation={[-Math.PI / 3, 0, 0]}
              />
              <mesh
                geometry={nodes.Blind7_Colors_0.geometry}
                material={materials.Colors}
                position={[50, 120, 157.5]}
                rotation={[-Math.PI / 3, 0, 0]}
              />
              <mesh
                geometry={nodes.Blind8_Colors_0.geometry}
                material={materials.Colors}
                position={[50, 110, 157.5]}
                rotation={[-Math.PI / 3, 0, 0]}
              />
              <mesh
                geometry={nodes.Blind9_Colors_0.geometry}
                material={materials.Colors}
                position={[50, 190, 157.5]}
                rotation={[-Math.PI / 3, 0, 0]}
              />
            </group>
            <group position={[-365, 275, 0]}>
              <group position={[25, 0, 30]}>
                <mesh
                  geometry={nodes.Top1_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-4, -25, -34.805]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[0.5, 1, 0.3]}
                />
                <mesh
                  geometry={nodes.Leg13_Colors_0.geometry}
                  material={materials.Colors}
                  position={[340, -275, 0]}
                />
                <mesh
                  geometry={nodes.Leg12_Colors_0.geometry}
                  material={materials.Colors}
                  position={[340, -275, 0]}
                />
              </group>
              <group position={[0, 0.039, -67.785]} scale={[1, 1.2, 0.5]}>
                <group position={[0, -0.032, 135.571]} scale={[1, 0.833, 2]}>
                  <mesh
                    geometry={nodes.Book1_Colors_0_2.geometry}
                    material={materials.Colors}
                    position={[-150, 212.467, -39.565]}
                  />
                  <mesh
                    geometry={nodes.Book2_Colors_0_2.geometry}
                    material={materials.Colors}
                    position={[-151, 212.467, -49.565]}
                  />
                  <mesh
                    geometry={nodes.Book3_Colors_0_1.geometry}
                    material={materials.Colors}
                    position={[-150, 212.467, -59.565]}
                  />
                  <mesh
                    geometry={nodes.Book4_Colors_0_1.geometry}
                    material={materials.Colors}
                    position={[-151, 212.467, -69.565]}
                  />
                  <mesh
                    geometry={nodes.Book14_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-150, 172.5, -63.363]}
                  />
                  <mesh
                    geometry={nodes.Book15_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151, 172.5, -73.363]}
                  />
                  <mesh
                    geometry={nodes.Book16_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-150, 172.5, -83.363]}
                  />
                  <mesh
                    geometry={nodes.Book17_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151, 172.5, -93.363]}
                  />
                  <mesh
                    geometry={nodes.Book18_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-150, 172.5, -103.6]}
                  />
                  <mesh
                    geometry={nodes.Book19_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151, 172.5, -113.6]}
                  />
                  <mesh
                    geometry={nodes.Book20_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-150, 172.5, -123.6]}
                  />
                  <mesh
                    geometry={nodes.Book21_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151, 172.5, -133.6]}
                  />
                  <mesh
                    geometry={nodes.Book22_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151, 137.806, -112.051]}
                    rotation={[0.297, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Book23_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-150, 137, -97.849]}
                  />
                  <mesh
                    geometry={nodes.Book24_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151, 137, -87.849]}
                  />
                  <mesh
                    geometry={nodes.Book25_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-150, 137, -77.849]}
                  />
                  <mesh
                    geometry={nodes.Book26_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151, 137, -67.613]}
                  />
                  <mesh
                    geometry={nodes.Book27_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-150, 137, -57.613]}
                  />
                  <mesh
                    geometry={nodes.Book28_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151, 137, -47.613]}
                  />
                  <mesh
                    geometry={nodes.Book29_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-150, 137, -37.613]}
                  />
                  <mesh
                    geometry={nodes.Book30_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-150, 97, -103.6]}
                  />
                  <mesh
                    geometry={nodes.Book31_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151, 97, -113.6]}
                  />
                  <mesh
                    geometry={nodes.Book32_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-150, 97, -123.6]}
                  />
                  <mesh
                    geometry={nodes.Book33_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151, 97, -133.6]}
                  />
                  <mesh
                    geometry={nodes.Book34_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-153.202, 87, -83.6]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Book35_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-151.192, 97.481, -83.136]}
                    rotation={[1.578, -0.034, 1.379]}
                  />
                  <mesh
                    geometry={nodes.Book36_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-152.968, 12.057, -77.844]}
                    rotation={[Math.PI / 2, 0, 0.562]}
                  />
                  <mesh
                    geometry={nodes.Book37_Colors_0.geometry}
                    material={materials.Colors}
                    position={[-149.538, 22.057, -80.188]}
                    rotation={[Math.PI / 2, 0, 0.809]}
                  />
                  <mesh
                    geometry={nodes.Book38_Colors_0.geometry}
                    material={materials.Colors}
                    position={[68.656, 86.018, 137.816]}
                    rotation={[Math.PI / 2, 0, 0]}
                  />
                  <mesh
                    geometry={nodes.Book39_Colors_0.geometry}
                    material={materials.Colors}
                    position={[69.286, 76.018, 138.403]}
                    rotation={[Math.PI / 2, 0, -1.658]}
                  />
                </group>
                <mesh
                  geometry={nodes.BookShelf_Colors_0.geometry}
                  material={materials.Colors}
                />
              </group>
              <group position={[25, 0, 0]}>
                <mesh
                  geometry={nodes.Laptop_Colors_0.geometry}
                  material={materials.Colors}
                  position={[1.818, 4.994, 73.819]}
                  rotation={[-Math.PI, 1.396, -Math.PI]}
                  scale={[0.308, 1, 0.268]}
                />
                <mesh
                  geometry={nodes.Paper_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-45.942, 54.5, 142.026]}
                  rotation={[0, -0.337, 0]}
                  scale={[0.3, 0.25, 0.25]}
                />
                <mesh
                  geometry={nodes.Top_Colors_0_2.geometry}
                  material={materials.Colors}
                  position={[45, 0, 0]}
                  rotation={[0, Math.PI / 2, 0]}
                />
                <mesh
                  geometry={nodes.Leg1_Colors_0_3.geometry}
                  material={materials.Colors}
                  position={[74.989, -10.526, 156.25]}
                  rotation={[Math.PI / 2, -0.262, Math.PI / 2]}
                  scale={[0.05, 1, 0.389]}
                />
                <mesh
                  geometry={nodes.Leg2_Colors_0_3.geometry}
                  material={materials.Colors}
                  position={[-20.931, -10.526, 143.75]}
                  rotation={[Math.PI / 2, 0.262, -Math.PI / 2]}
                  scale={[0.05, 1, 0.389]}
                />
                <mesh
                  geometry={nodes.Leg3_Colors_0_3.geometry}
                  material={materials.Colors}
                  position={[-20.931, -10.526, 93.75]}
                  rotation={[Math.PI / 2, 0.262, -Math.PI / 2]}
                  scale={[0.05, 1, 0.389]}
                />
                <mesh
                  geometry={nodes.Leg4_Colors_0_2.geometry}
                  material={materials.Colors}
                  position={[74.989, -10.526, 106.25]}
                  rotation={[Math.PI / 2, -0.262, Math.PI / 2]}
                  scale={[0.05, 1, 0.389]}
                />
                <mesh
                  geometry={nodes.Leg8_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-25.046, -10.526, 156.25]}
                  rotation={[Math.PI / 2, -0.262, Math.PI / 2]}
                  scale={[0.05, 1, 0.389]}
                />
                <mesh
                  geometry={nodes.Leg9_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-120.965, -10.526, 143.75]}
                  rotation={[Math.PI / 2, 0.262, -Math.PI / 2]}
                  scale={[0.05, 1, 0.389]}
                />
                <mesh
                  geometry={nodes.Leg10_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-120.965, -10.526, 93.75]}
                  rotation={[Math.PI / 2, 0.262, -Math.PI / 2]}
                  scale={[0.05, 1, 0.389]}
                />
                <mesh
                  geometry={nodes.Leg11_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-25.046, -10.526, 106.25]}
                  rotation={[Math.PI / 2, -0.262, Math.PI / 2]}
                  scale={[0.05, 1, 0.389]}
                />
                <mesh
                  geometry={nodes.Box_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-149.373, 25.5, -51.461]}
                  rotation={[0, 0.204, 0]}
                  scale={[0.201, 0.25, 0.168]}
                />
                <mesh
                  geometry={nodes.Box1_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-154.814, 25.5, -90.502]}
                  rotation={[0, -0.233, 0]}
                  scale={[0.201, 0.25, 0.168]}
                />
                <mesh
                  geometry={nodes.Box2_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-153.961, -9.5, -101.623]}
                  rotation={[0, -0.194, 0]}
                  scale={[0.201, 0.25, 0.168]}
                />
                <mesh
                  geometry={nodes.Box3_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-162.45, -9.5, -69.457]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[0.201, 0.25, 0.168]}
                />
                <mesh
                  geometry={nodes.Paper7_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-45.942, -16.5, -31.415]}
                  rotation={[0, -0.337, 0]}
                  scale={[0.3, 0.25, 0.25]}
                />
                <mesh
                  geometry={nodes.Paper8_Colors_0.geometry}
                  material={materials.Colors}
                  position={[11.734, -16.5, -51.89]}
                  rotation={[0, -1.239, 0]}
                  scale={[0.3, 0.25, 0.25]}
                />
              </group>
              <group
                position={[-72.5, 200, 165.396]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[1, 1.2, 0.5]}
              >
                <mesh
                  geometry={nodes.Picture13_Colors_0.geometry}
                  material={materials.Colors}
                  position={[5, 7.221, 0]}
                />
                <mesh
                  geometry={nodes.Picture12_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-33.296, 6.114, 0]}
                />
                <mesh
                  geometry={nodes.Picture11_Colors_0.geometry}
                  material={materials.Colors}
                  position={[79.878, 0, 0]}
                />
                <mesh
                  geometry={nodes.Picture10_Colors_0.geometry}
                  material={materials.Colors}
                  position={[5, 0, 0]}
                />
                <mesh
                  geometry={nodes.Picture9_Colors_0.geometry}
                  material={materials.Colors}
                  position={[5, 7.221, 0]}
                />
              </group>
              <group position={[-200, 0, 50]}>
                <mesh
                  geometry={nodes.pCube11_Colors_0.geometry}
                  material={materials.Colors}
                  position={[50, 110.428, -46.778]}
                  scale={1.1}
                />
                <mesh
                  geometry={nodes.pCube10_Colors_0.geometry}
                  material={materials.Colors}
                  position={[50, 60, -50]}
                />
                <mesh
                  geometry={nodes.pCube9_Colors_0.geometry}
                  material={materials.Colors}
                  position={[50, 20, -50]}
                />
                <mesh
                  geometry={nodes.pCube12_Colors_0.geometry}
                  material={materials.Colors}
                  position={[43.674, 62.49, -50]}
                  rotation={[0, 0, 0.627]}
                  scale={0.685}
                />
                <mesh
                  geometry={nodes.pCube13_Colors_0.geometry}
                  material={materials.Colors}
                  position={[35.573, 82.173, -53.049]}
                  scale={0.518}
                />
                <mesh
                  geometry={nodes.pCube16_Colors_0.geometry}
                  material={materials.Colors}
                  position={[66.425, 116.858, -58.802]}
                  scale={0.518}
                />
              </group>
              <group position={[-48.618, 70.96, 175.315]} scale={0.455}>
                <mesh
                  geometry={nodes.pCube11_Colors_0_1.geometry}
                  material={materials.Colors}
                  position={[50, 110.428, -50]}
                  scale={1.1}
                />
                <mesh
                  geometry={nodes.pCube10_Colors_0_1.geometry}
                  material={materials.Colors}
                  position={[50, 60, -50]}
                />
                <mesh
                  geometry={nodes.pCube9_Colors_0_1.geometry}
                  material={materials.Colors}
                  position={[50, 20, -50]}
                />
                <mesh
                  geometry={nodes.pCube12_Colors_0_1.geometry}
                  material={materials.Colors}
                  position={[-24.989, 6.927, -39.887]}
                  rotation={[0, -0.755, 0]}
                />
                <mesh
                  geometry={nodes.pCube13_Colors_0_1.geometry}
                  material={materials.Colors}
                  position={[45.003, 89.1, -62.393]}
                  scale={0.518}
                />
                <mesh
                  geometry={nodes.pCube16_Colors_0_1.geometry}
                  material={materials.Colors}
                  position={[66.425, 116.858, -47.874]}
                  scale={0.518}
                />
              </group>
              <mesh
                geometry={nodes.Walls2_Colors_0_1.geometry}
                material={materials.Colors}
                position={[365, -275, 0]}
              />
              <group position={[60, 0, 0]}>
                <mesh
                  geometry={nodes.Cork_Board2_Colors_0.geometry}
                  material={materials.Colors}
                  position={[50, 150, 172.5]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1, 2, 2]}
                />
                <mesh
                  geometry={nodes.Paper3_Colors_0.geometry}
                  material={materials.Colors}
                  position={[107.344, 172.365, 152]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.3, 0.25, 0.141]}
                />
                <mesh
                  geometry={nodes.Paper4_Colors_0.geometry}
                  material={materials.Colors}
                  position={[103.888, 121.006, 152]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.3, 0.25, 0.25]}
                />
                <mesh
                  geometry={nodes.Paper5_Colors_0.geometry}
                  material={materials.Colors}
                  position={[68.012, 135.556, 152]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.3, 0.25, 0.25]}
                />
              </group>
              <group position={[-60, 0, 0]}>
                <mesh
                  geometry={nodes.Paper6_Colors_0.geometry}
                  material={materials.Colors}
                  position={[6.626, 144.201, 152]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.3, 0.25, 0.25]}
                />
                <mesh
                  geometry={nodes.Paper2_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-32.905, 159.569, 152]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.3, 0.25, 0.2]}
                />
                <mesh
                  geometry={nodes.Paper1_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-30.426, 113.971, 152]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.3, 0.25, 0.2]}
                />
                <mesh
                  geometry={nodes.Cork_Board1_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-50, 150, 172.5]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[1, 2, 2]}
                />
              </group>
              <mesh
                geometry={nodes.Container1_Colors_0.geometry}
                material={materials.Colors}
                position={[123.862, 5.178, 109.969]}
                rotation={[0.008, -1.115, 0.013]}
                scale={1.485}
              />
              <mesh
                geometry={nodes.Paper_Roll_Colors_0.geometry}
                material={materials.Colors}
                position={[-72.395, 10.379, -77.372]}
                rotation={[Math.PI / 2, 0, 0.626]}
              />
            </group>
            <group position={[365, 0, 365]}>
              <group position={[365, 0, -355]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh
                  geometry={nodes.Cushion_Top1_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Cushion_Top2_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Cushion_Top3_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Cushion_Bottom1_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Cushion_Bottom2_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Cushion_Bottom3_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Cushion_Top4_Colors_0.geometry}
                  material={materials.Colors}
                  position={[63.691, 57.841, 351.347]}
                  rotation={[0.154, 0.653, -0.094]}
                  scale={0.65}
                />
                <mesh
                  geometry={nodes.Cushion_Top5_Colors_0.geometry}
                  material={materials.Colors}
                  position={[45.554, 57.841, 351.347]}
                  rotation={[0.154, 0.653, -0.094]}
                  scale={0.65}
                />
                <mesh
                  geometry={nodes.Cushion_Top6_Colors_0.geometry}
                  material={materials.Colors}
                  position={[402.587, 18.836, 139.181]}
                  rotation={[-0.028, -1.029, -0.056]}
                  scale={0.65}
                />
                <mesh
                  geometry={nodes.Frame_Back_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Frame_Bottom_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Leg1_Colors_0_1.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Leg2_Colors_0_1.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Leg3_Colors_0_1.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Leg4_Colors_0.geometry}
                  material={materials.Colors}
                />
              </group>
              <group
                position={[321.492, 0, -384.877]}
                rotation={[0, -Math.PI / 2, 0]}
              >
                <mesh
                  geometry={nodes.Table_Body_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Handle_Colors_0_2.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Drawer_Colors_0_1.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Leg1_Colors_0_2.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Leg2_Colors_0_2.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Leg3_Colors_0_2.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Leg4_Colors_0_1.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Tissue_Box_Colors_0.geometry}
                  material={materials.Colors}
                />
              </group>
              <group
                position={[83.435, 0, -26.565]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={0.8}
              >
                <mesh
                  geometry={nodes.TV_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Dresser_Colors_0.geometry}
                  material={materials.Colors}
                />
              </group>
              <group position={[100, 0, -75]}>
                <mesh
                  geometry={nodes.pCube11_Colors_0_2.geometry}
                  material={materials.Colors}
                  position={[50, 100, -50]}
                />
                <mesh
                  geometry={nodes.pCube10_Colors_0_2.geometry}
                  material={materials.Colors}
                  position={[50, 60, -50]}
                />
                <mesh
                  geometry={nodes.pCube9_Colors_0_2.geometry}
                  material={materials.Colors}
                  position={[50, 20, -50]}
                />
              </group>
              <mesh
                geometry={nodes.Walls_Colors_0.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.Picture_Colors_0_1.geometry}
                material={materials.Colors}
                position={[10, 170, 172.5]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Picture1_Colors_0.geometry}
                material={materials.Colors}
                position={[-96.002, 175, 172.5]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Picture2_Colors_0.geometry}
                material={materials.Colors}
                position={[-40.985, 175, 172.5]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Picture3_Colors_0.geometry}
                material={materials.Colors}
                position={[-90, 120, 172.5]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Picture4_Colors_0.geometry}
                material={materials.Colors}
                position={[-30, 120, 172.5]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Picture6_Colors_0.geometry}
                material={materials.Colors}
                position={[-172.5, 175, -120]}
                scale={[1, 1.5, 1.5]}
              />
              <mesh
                geometry={nodes.Picture7_Colors_0.geometry}
                material={materials.Colors}
                position={[-172.5, 175, 70]}
                scale={[1, 1.5, 1.5]}
              />
              <mesh
                geometry={nodes.Picture8_Colors_0.geometry}
                material={materials.Colors}
                position={[-172.5, 175, -25]}
                scale={[1, 2, 2]}
              />
            </group>
            <group position={[-365, 0, -365]}>
              <group position={[-59.877, 0, 43.687]}>
                <mesh
                  geometry={nodes.polySurface1_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.polySurface2_Colors_0.geometry}
                  material={materials.Colors}
                />
              </group>
              <group position={[65, 0, 40]} rotation={[-Math.PI, 0, -Math.PI]}>
                <group scale={[1, 1, 1.5]}>
                  <group scale={[1, 1, 0.667]}>
                    <mesh
                      geometry={nodes.polySurface10_Colors_0.geometry}
                      material={materials.Colors}
                      position={[0, 0, 22.5]}
                    />
                    <mesh
                      geometry={nodes.polySurface11_Colors_0.geometry}
                      material={materials.Colors}
                      position={[0, 0, -26.5]}
                    />
                  </group>
                  <mesh
                    geometry={nodes.polySurface4_Colors_0.geometry}
                    material={materials.Colors}
                  />
                  <mesh
                    geometry={nodes.polySurface7_Colors_0.geometry}
                    material={materials.Colors}
                    position={[9.603, 0, 0]}
                  />
                </group>
                <mesh
                  geometry={nodes.Matress_Colors_0.geometry}
                  material={materials.Colors}
                  scale={[1, 1, 1.5]}
                />
                <mesh
                  geometry={nodes.Pillow1_Colors_0.geometry}
                  material={materials.Colors}
                  position={[7.222, -23.828, -42.5]}
                  rotation={[0, 0, 0.122]}
                />
                <mesh
                  geometry={nodes.Pillow2_Colors_0.geometry}
                  material={materials.Colors}
                  position={[7.222, -23.828, 42.5]}
                  rotation={[0, 0, 0.122]}
                />
              </group>
              <mesh
                geometry={nodes.Walls_Colors_0_2.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.Curtain_Holder_Colors_0.geometry}
                material={materials.Colors}
                position={[0, 200, 165]}
              />
              <mesh
                geometry={nodes.Blind1_Colors_0_1.geometry}
                material={materials.Colors}
                position={[90, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind2_Colors_0_1.geometry}
                material={materials.Colors}
                position={[80, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind3_Colors_0_1.geometry}
                material={materials.Colors}
                position={[70, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind4_Colors_0_1.geometry}
                material={materials.Colors}
                position={[60, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind5_Colors_0_1.geometry}
                material={materials.Colors}
                position={[50, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind6_Colors_0_1.geometry}
                material={materials.Colors}
                position={[40, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind7_Colors_0_1.geometry}
                material={materials.Colors}
                position={[30, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind8_Colors_0_1.geometry}
                material={materials.Colors}
                position={[20, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind9_Colors_0_1.geometry}
                material={materials.Colors}
                position={[10, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind10_Colors_0.geometry}
                material={materials.Colors}
                position={[0, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind11_Colors_0.geometry}
                material={materials.Colors}
                position={[-10, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind12_Colors_0.geometry}
                material={materials.Colors}
                position={[-20, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind13_Colors_0.geometry}
                material={materials.Colors}
                position={[-30, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind14_Colors_0.geometry}
                material={materials.Colors}
                position={[-40, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind15_Colors_0.geometry}
                material={materials.Colors}
                position={[-50, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind16_Colors_0.geometry}
                material={materials.Colors}
                position={[-60, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind17_Colors_0.geometry}
                material={materials.Colors}
                position={[-70, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Blind18_Colors_0.geometry}
                material={materials.Colors}
                position={[-80, 100, 165]}
                rotation={[0, Math.PI / 6, 0]}
              />
              <mesh
                geometry={nodes.Airconditioner_Colors_0.geometry}
                material={materials.Colors}
                position={[-160, 220, 60]}
              />
              <mesh
                geometry={nodes.Picture1_Colors_0_1.geometry}
                material={materials.Colors}
                position={[-172.464, 140, 100]}
                scale={[1, 2, 2]}
              />
              <mesh
                geometry={nodes.Picture2_Colors_0_1.geometry}
                material={materials.Colors}
                position={[-172.464, 140, 0]}
                scale={[1, 2, 2]}
              />
              <mesh
                geometry={nodes.Picture3_Colors_0_1.geometry}
                material={materials.Colors}
                position={[-172.464, 140, -100]}
                scale={[1, 2, 2]}
              />
              <mesh
                geometry={nodes.pCube17_Colors_0.geometry}
                material={materials.Colors}
                position={[-150, 30, -100]}
              />
              <mesh
                geometry={nodes.pCube18_Colors_0.geometry}
                material={materials.Colors}
                position={[-127.305, 45.957, -100]}
              />
              <mesh
                geometry={nodes.pCube19_Colors_0.geometry}
                material={materials.Colors}
                position={[-127.305, 19.16, -100]}
              />
              <mesh
                geometry={nodes.pCube20_Colors_0.geometry}
                material={materials.Colors}
                position={[-120.931, 49.327, -100]}
              />
              <mesh
                geometry={nodes.pCube21_Colors_0.geometry}
                material={materials.Colors}
                position={[-120.931, 23.043, -100]}
              />
              <mesh
                geometry={nodes.Book41_Colors_0.geometry}
                material={materials.Colors}
                position={[-152.082, 65.007, -111.683]}
                rotation={[Math.PI / 2, 0, -1.658]}
              />
              <mesh
                geometry={nodes.Book40_Colors_0.geometry}
                material={materials.Colors}
                position={[-152.711, 75.007, -112.27]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Carpet2_Colors_0.geometry}
                material={materials.Colors}
                position={[80, 1.5, 50]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[1.35, 0.025, 0.9]}
              />
            </group>
            <group position={[365, -275, 0]}>
              <group position={[-167, 0, -7.5]} scale={[20, 20, 25]}>
                <mesh
                  geometry={nodes.tap_low_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.stopper_low_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.soap_low_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.sink_low_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Sink_Shelf_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-9.9, 13.75, 0.3]}
                  scale={[0.05, 0.05, 0.04]}
                />
                <mesh
                  geometry={nodes.Mirror_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-0.275, 8.75, -4.1]}
                  scale={[0.05, 0.1, 0.08]}
                />
              </group>
              <group position={[-158.5, 0, -10]} scale={20}>
                <mesh
                  geometry={nodes.tank_low_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.flush_low_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.lid_low_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.bowl_low_Colors_0.geometry}
                  material={materials.Colors}
                />
              </group>
              <group position={[0, 0, -25]}>
                <mesh
                  geometry={nodes.pCube5_Colors_0.geometry}
                  material={materials.Colors}
                  position={[115, 75, 173.5]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[1, 0.9, 0.75]}
                />
                <mesh
                  geometry={nodes.pCube4_Colors_0.geometry}
                  material={materials.Colors}
                  position={[115, 160, 184.5]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[1, 0.9, 0.75]}
                />
                <mesh
                  geometry={nodes.pCube3_Colors_0.geometry}
                  material={materials.Colors}
                  position={[115, 120, 180]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[1, 0.9, 0.75]}
                />
                <mesh
                  geometry={nodes.pCube2_Colors_0.geometry}
                  material={materials.Colors}
                  position={[70, 100.473, 177.261]}
                  rotation={[0.122, 0, 0]}
                  scale={[1, 2, 1]}
                />
                <mesh
                  geometry={nodes.pCube1_Colors_0.geometry}
                  material={materials.Colors}
                  position={[160, 100.473, 177.261]}
                  rotation={[0.122, 0, 0]}
                  scale={[1, 2, 1]}
                />
              </group>
              <group
                position={[99.098, 125, 154.442]}
                rotation={[0, -0.154, 0]}
              >
                <mesh
                  geometry={nodes.Tray_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.soap_low2_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-49.305, -141.137, 108.373]}
                  rotation={[0, -0.428, 0]}
                  scale={[31.368, 29.611, 34.94]}
                />
                <mesh
                  geometry={nodes.soap_low1_Colors_0.geometry}
                  material={materials.Colors}
                  position={[31.697, -141.137, 121.108]}
                  rotation={[0, 0.154, 0]}
                  scale={[29.611, 29.611, 37.013]}
                />
              </group>
              <group position={[100, 0, -50]}>
                <mesh
                  geometry={nodes.pCube11_Colors_0_3.geometry}
                  material={materials.Colors}
                  position={[50, 100, -50]}
                />
                <mesh
                  geometry={nodes.pCube10_Colors_0_3.geometry}
                  material={materials.Colors}
                  position={[50, 60, -50]}
                />
                <mesh
                  geometry={nodes.pCube9_Colors_0_3.geometry}
                  material={materials.Colors}
                  position={[50, 20, -50]}
                />
                <mesh
                  geometry={nodes.pCube14_Colors_0.geometry}
                  material={materials.Colors}
                  position={[35.573, 92.429, -36.606]}
                  scale={0.518}
                />
                <mesh
                  geometry={nodes.pCube15_Colors_0.geometry}
                  material={materials.Colors}
                  position={[62.353, 105.69, -61.97]}
                  scale={0.518}
                />
              </group>
              <group position={[100, 0, -100]}>
                <mesh
                  geometry={nodes.pCube11_Colors_0_4.geometry}
                  material={materials.Colors}
                  position={[50, 110.428, -50]}
                  scale={1.1}
                />
                <mesh
                  geometry={nodes.pCube10_Colors_0_4.geometry}
                  material={materials.Colors}
                  position={[50, 60, -50]}
                />
                <mesh
                  geometry={nodes.pCube9_Colors_0_4.geometry}
                  material={materials.Colors}
                  position={[50, 20, -50]}
                />
                <mesh
                  geometry={nodes.pCube12_Colors_0_2.geometry}
                  material={materials.Colors}
                  position={[43.674, 62.49, -50]}
                  rotation={[0, 0, 0.627]}
                  scale={0.685}
                />
                <mesh
                  geometry={nodes.pCube13_Colors_0_2.geometry}
                  material={materials.Colors}
                  position={[35.573, 82.173, -53.049]}
                  scale={0.518}
                />
                <mesh
                  geometry={nodes.pCube16_Colors_0_2.geometry}
                  material={materials.Colors}
                  position={[66.425, 116.858, -47.874]}
                  scale={0.518}
                />
              </group>
              <mesh
                geometry={nodes.Tissue_Box1_Colors_0.geometry}
                material={materials.Colors}
                position={[-289.414, 73.5, 194.201]}
                rotation={[0, 0.905, 0]}
              />
              <mesh
                geometry={nodes.Walls_Colors_0_3.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.Rod_Colors_0.geometry}
                material={materials.Colors}
                position={[-62.5, 225, 50]}
              />
              <mesh
                geometry={nodes.Curtain_Colors_0.geometry}
                material={materials.Colors}
                position={[-90, 115, 46.5]}
              />
              <mesh
                geometry={nodes.Tub_Colors_0.geometry}
                material={materials.Colors}
                position={[-62.5, 35, 112.5]}
              />
              <mesh
                geometry={nodes.Handle_Colors_0.geometry}
                material={materials.Colors}
                position={[-65, 112.5, 165]}
                scale={[0.681, 1, 1]}
              />
              <mesh
                geometry={nodes.Showhead_Colors_0.geometry}
                material={materials.Colors}
                position={[-105.606, 0.907, 282.31]}
                scale={[40.918, 40.918, 51.148]}
              />
              <mesh
                geometry={nodes.Showerpipe_Colors_0.geometry}
                material={materials.Colors}
                position={[-162, 220, 112.5]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.681, 1, 1]}
              />
              <mesh
                geometry={nodes.Showerpipe1_Colors_0.geometry}
                material={materials.Colors}
                position={[-162, 87.038, 112.5]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.681, 1, 1]}
              />
              <mesh
                geometry={nodes.stopper_low1_Colors_0.geometry}
                material={materials.Colors}
                position={[-75, -75, 218]}
                scale={[20, 20, 25]}
              />
              <mesh
                geometry={nodes.Carpet_Colors_0_1.geometry}
                material={materials.Colors}
                position={[-35, 1, -2.5]}
                scale={[1.35, 0.025, 0.9]}
              />
              <mesh
                geometry={nodes.Bottle1_Colors_0.geometry}
                material={materials.Colors}
                position={[105.829, 168.781, 160.991]}
                rotation={[0, 0.262, 0]}
                scale={0.126}
              />
              <mesh
                geometry={nodes.Bottle2_Colors_0.geometry}
                material={materials.Colors}
                position={[121.335, 168.781, 158.522]}
                rotation={[0, -0.105, 0]}
                scale={0.126}
              />
              <mesh
                geometry={nodes.Bottle3_Colors_0.geometry}
                material={materials.Colors}
                position={[144.757, 83.781, 149.355]}
                rotation={[0, 0.174, 0]}
                scale={0.126}
              />
              <mesh
                geometry={nodes.Bottle4_Colors_0.geometry}
                material={materials.Colors}
                position={[83.288, 83.781, 147.84]}
                rotation={[0, -0.011, 0]}
                scale={0.126}
              />
              <mesh
                geometry={nodes.Bottle5_Colors_0.geometry}
                material={materials.Colors}
                position={[127.843, 85, 149.217]}
                rotation={[0, -0.012, 0]}
                scale={0.15}
              />
              <mesh
                geometry={nodes.Bottle6_Colors_0.geometry}
                material={materials.Colors}
                position={[86.199, 170, 158.75]}
                rotation={[0, -Math.PI / 9, 0]}
                scale={0.15}
              />
              <mesh
                geometry={nodes.Container_Colors_0.geometry}
                material={materials.Colors}
                position={[-154.038, 34.984, -127.585]}
                rotation={[0.008, -1.115, 0.013]}
              />
              <mesh
                geometry={nodes.Toilet_Paper_Colors_0.geometry}
                material={materials.Colors}
                position={[-149.97, 39, -73.197]}
              />
              <mesh
                geometry={nodes.Toilet_Paper1_Colors_0.geometry}
                material={materials.Colors}
                position={[-163.186, 39, -90.363]}
                rotation={[0, -0.57, 0]}
              />
              <mesh
                geometry={nodes.Toilet_Paper2_Colors_0.geometry}
                material={materials.Colors}
                position={[-158.865, 51.492, -82.511]}
                rotation={[0, 0.449, 0]}
              />
              <mesh
                geometry={nodes.Picture_Colors_0_2.geometry}
                material={materials.Colors}
                position={[-172.5, 193.023, 4.84]}
                scale={[1, 0.985, 0.985]}
              />
              <mesh
                geometry={nodes.Picture14_Colors_0.geometry}
                material={materials.Colors}
                position={[-172.5, 175.879, -38.809]}
              />
              <mesh
                geometry={nodes.Picture15_Colors_0.geometry}
                material={materials.Colors}
                position={[-172.5, 144.684, -0.618]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[1, 0.673, 0.673]}
              />
              <mesh
                geometry={nodes.Carpet1_Colors_0.geometry}
                material={materials.Colors}
                position={[117.209, 32.774, 128.086]}
                scale={[0.56, 0.056, 0.373]}
              />
            </group>
            <group position={[0, -275, -365]}>
              <group position={[-29.192, 0, 65.768]}>
                <mesh
                  geometry={nodes.Side_Left_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125, 50, 100]}
                />
                <mesh
                  geometry={nodes.Side_Right_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125, 50, -50]}
                />
                <mesh
                  geometry={nodes.Shelf_Bottom_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-127.5, 35, 25]}
                  rotation={[0, 0, -0.262]}
                />
                <mesh
                  geometry={nodes.Shelf_Top_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-127.5, 70, 25]}
                  rotation={[0, 0, -0.262]}
                />
                <mesh
                  geometry={nodes.Dumbell1_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 80, 60]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell2_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 80, 80]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell3_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 80, 40]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell4_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 80, 20]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell5_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 80, 0]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell6_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 80, -20]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell7_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 45, 70]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell8_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 45, 50]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell9_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 45, 30]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell10_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 45, 10]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell11_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 45, -10]}
                  rotation={[0, 0, 1.309]}
                />
                <mesh
                  geometry={nodes.Dumbell12_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-125.537, 45, -30]}
                  rotation={[0, 0, 1.309]}
                />
              </group>
              <group position={[30, 0, 20]} scale={0.8}>
                <mesh
                  geometry={nodes.Treadmill_Panel_Colors_0.geometry}
                  material={materials.Colors}
                  position={[75, 125, 135]}
                  rotation={[-Math.PI / 6, 0, 0]}
                  scale={[1, 1, 0.2]}
                />
                <mesh
                  geometry={nodes.Treadmill_base_Colors_0.geometry}
                  material={materials.Colors}
                  position={[75, 10, 55]}
                />
              </group>
              <mesh
                geometry={nodes.Walls1_Colors_0.geometry}
                material={materials.Colors}
              />
              <mesh
                geometry={nodes.TV1_Colors_0.geometry}
                material={materials.Colors}
                position={[-130.111, 110.922, 49.597]}
                rotation={[Math.PI / 2, 1.309, -Math.PI / 2]}
                scale={0.548}
              />
              <mesh
                geometry={nodes.YogaBall_Colors_0.geometry}
                material={materials.Colors}
                position={[-84.108, 25, 137.153]}
                rotation={[-0.475, 0.103, -0.501]}
              />
              <mesh
                geometry={nodes.Seat_Colors_0.geometry}
                material={materials.Colors}
                position={[-150, 40, -80]}
              />
              <mesh
                geometry={nodes.Leg_Colors_0.geometry}
                material={materials.Colors}
                position={[-150, 5, -150]}
              />
              <mesh
                geometry={nodes.Leg5_Colors_0.geometry}
                material={materials.Colors}
                position={[-150, 5, -10]}
              />
              <mesh
                geometry={nodes.Leg6_Colors_0.geometry}
                material={materials.Colors}
                position={[-150, 21.054, -20.228]}
                rotation={[-Math.PI / 6, 0, 0]}
                scale={[0.178, 3.585, 0.67]}
              />
              <mesh
                geometry={nodes.Leg7_Colors_0.geometry}
                material={materials.Colors}
                position={[-150, 21.054, -139.457]}
                rotation={[Math.PI / 6, 0, 0]}
                scale={[0.178, 3.585, 0.67]}
              />
              <mesh
                geometry={nodes.Cork_Board_Colors_0.geometry}
                material={materials.Colors}
                position={[-175, 150, -80]}
                scale={[1, 2, 2]}
              />
              <mesh
                geometry={nodes.pCube8_Colors_0.geometry}
                material={materials.Colors}
                position={[-34.426, 1, -79.69]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[1.35, 0.025, 0.9]}
              />
              <mesh
                geometry={nodes.YogaBall1_Colors_0.geometry}
                material={materials.Colors}
                position={[-29.034, 25, 123.128]}
                rotation={[-0.758, 0.1, 0.479]}
              />
              <mesh
                geometry={nodes.Note1_Colors_0.geometry}
                material={materials.Colors}
                position={[-171.509, 145.742, -57.379]}
                rotation={[0.087, 0, 0]}
              />
              <mesh
                geometry={nodes.Note2_Colors_0.geometry}
                material={materials.Colors}
                position={[-171.509, 173.045, -102.135]}
                rotation={[-0.052, 0, 0]}
              />
              <mesh
                geometry={nodes.Note3_Colors_0.geometry}
                material={materials.Colors}
                position={[-171.509, 172.111, -63.893]}
              />
              <mesh
                geometry={nodes.Note4_Colors_0.geometry}
                material={materials.Colors}
                position={[-171.509, 126.432, -103.22]}
              />
              <mesh
                geometry={nodes.Note5_Colors_0.geometry}
                material={materials.Colors}
                position={[-171.509, 169.029, -78.028]}
              />
              <mesh
                geometry={nodes.Note6_Colors_0.geometry}
                material={materials.Colors}
                position={[-171.509, 132.669, -64.332]}
              />
            </group>
            <group position={[-10, 0, 0]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh
                geometry={nodes.pCube7_Colors_0.geometry}
                material={materials.Colors}
                position={[30, 167.5, 152.5]}
              />
              <mesh
                geometry={nodes.Pan_Colors_0.geometry}
                material={materials.Colors}
                position={[29.572, 133.75, 148.779]}
                rotation={[Math.PI / 2, 0, 2.793]}
              />
              <mesh
                geometry={nodes.Pan1_Colors_0.geometry}
                material={materials.Colors}
                position={[-5.428, 133.75, 148.779]}
                rotation={[Math.PI / 2, 0, 2.793]}
              />
              <mesh
                geometry={nodes.Pan2_Colors_0.geometry}
                material={materials.Colors}
                position={[64.572, 133.75, 148.779]}
                rotation={[Math.PI / 2, 0, 2.793]}
              />
              <mesh
                geometry={nodes.Pan3_Colors_0.geometry}
                material={materials.Colors}
                position={[130.029, 104.611, -81.174]}
                rotation={[-Math.PI, 1.073, -Math.PI]}
              />
            </group>
            <group scale={[1, 0.9, 1]}>
              <group
                position={[-21.081, -150.075, 353.516]}
                scale={[100, 111.111, 100]}
              >
                <mesh
                  geometry={nodes.Cup_Colors_0.geometry}
                  material={materials.Colors}
                  position={[0.076, 0, -0.069]}
                />
                <mesh
                  geometry={nodes.Cup1_Colors_0.geometry}
                  material={materials.Colors}
                  position={[-2.495, 0, -0.973]}
                  rotation={[0, -1.29, 0]}
                />
                <mesh
                  geometry={nodes.Cup2_Colors_0.geometry}
                  material={materials.Colors}
                  position={[1.273, 0, -0.804]}
                  rotation={[0, 0.755, 0]}
                />
              </group>
              <group
                position={[-322.593, -24.945, 69.18]}
                rotation={[-Math.PI, -1.284, -Math.PI]}
                scale={[100, 111.111, 100]}
              >
                <mesh
                  geometry={nodes.Button_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Button1_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Cap_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Jug_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Base_Colors_0.geometry}
                  material={materials.Colors}
                />
              </group>
              <mesh
                geometry={nodes.Stove_Top_Colors_0.geometry}
                material={materials.Colors}
                position={[48.199, 106.2, 119.276]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 1, 0.85]}
              />
              <mesh
                geometry={nodes.Counter_Colors_0.geometry}
                material={materials.Colors}
                position={[-125, 50, 125]}
              />
              <group
                position={[86.393, 47.5, 73]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[1, 1, 0.85]}
              >
                <mesh
                  geometry={nodes.Door1_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Handle1_Colors_0_1.geometry}
                  material={materials.Colors}
                  position={[5.975, 0, 27.773]}
                  scale={[1, 0.5, 0.068]}
                />
              </group>
              <group
                position={[24.393, 47.5, 73]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[1, 1, 0.85]}
              >
                <mesh
                  geometry={nodes.Door2_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Handle2_Colors_0_1.geometry}
                  material={materials.Colors}
                  position={[5.975, 0, 26.072]}
                  scale={[1, 0.5, 0.068]}
                />
              </group>
              <group
                position={[-37.607, 47.5, 73]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[1, 1, 0.85]}
              >
                <mesh
                  geometry={nodes.Door3_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Handle3_Colors_0_1.geometry}
                  material={materials.Colors}
                  position={[5.975, 0, 26.565]}
                  scale={[1, 0.5, 0.068]}
                />
              </group>
              <group
                position={[-41.335, 47.5, 48.81]}
                rotation={[0, -1.248, 0]}
              >
                <mesh
                  geometry={nodes.Door4_Colors_0.geometry}
                  material={materials.Colors}
                />
                <mesh
                  geometry={nodes.Handle4_Colors_0.geometry}
                  material={materials.Colors}
                  position={[6, 0, -29.5]}
                  scale={[1, 0.5, 0.057]}
                />
              </group>
              <mesh
                geometry={nodes.Trash_Colors_0.geometry}
                material={materials.Colors}
                position={[-105.954, 36.127, 26.451]}
                rotation={[0, 0.175, 0]}
                scale={[0.497, 0.552, 0.497]}
              />
              <mesh
                geometry={nodes.Tap_Colors_0.geometry}
                material={materials.Colors}
                position={[-145, 121.667, 25]}
                scale={[1, 1.111, 1]}
              />
              <mesh
                geometry={nodes.Hot_Colors_0.geometry}
                material={materials.Colors}
                position={[-145, 122.222, 35]}
                scale={[1, 1.111, 1]}
              />
              <mesh
                geometry={nodes.Cold_Colors_0.geometry}
                material={materials.Colors}
                position={[-145, 122.222, 15]}
                scale={[1, 1.111, 1]}
              />
              <mesh
                geometry={nodes.Cold1_Colors_0.geometry}
                material={materials.Colors}
                position={[-112.5, 99.525, 25]}
                scale={[1, 1.111, 1]}
              />
              <mesh
                geometry={nodes.Stove_Top1_Colors_0.geometry}
                material={materials.Colors}
                position={[48.778, 109, 91.503]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 1, 0.85]}
              />
              <mesh
                geometry={nodes.Stove_Top2_Colors_0.geometry}
                material={materials.Colors}
                position={[48.778, 109, 129.821]}
                rotation={[Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 1, 0.85]}
              />
              <mesh
                geometry={
                  nodes
                    .Thing_above_the_stove_i_dont_really_know_wat_its_called_Colors_0
                    .geometry
                }
                material={materials.Colors}
                position={[503.433, -57.771, 455.69]}
                scale={[100, 111.111, 100]}
              />
            </group>
            <group rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh
                geometry={nodes.Metal_Colors_0.geometry}
                material={materials.Colors}
                position={[-150, 40, -152.5]}
                rotation={[Math.PI, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Paper_Colors_0_1.geometry}
                material={materials.Colors}
                position={[-150, 40, -110]}
                rotation={[Math.PI, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Plastic_Colors_0.geometry}
                material={materials.Colors}
                position={[-150, 40, -67.5]}
                rotation={[Math.PI, 0, -Math.PI]}
              />
            </group>
            <mesh
              geometry={nodes.Walls_Colors_0_1.geometry}
              material={materials.Colors}
            />
            <mesh
              geometry={nodes.Top_Shelf_Colors_0.geometry}
              material={materials.Colors}
              position={[-137.5, 190, 137.5]}
            />
            <mesh
              geometry={nodes.Book1_Colors_0.geometry}
              material={materials.Colors}
              position={[-117.367, 100, 141.721]}
              rotation={[-Math.PI / 2, 0, 0.175]}
            />
            <mesh
              geometry={nodes.Book2_Colors_0.geometry}
              material={materials.Colors}
              position={[-117.367, 110, 145.986]}
              rotation={[-Math.PI / 2, 0, Math.PI / 6]}
            />
            <mesh
              geometry={nodes.Ice_Dispenser_Colors_0.geometry}
              material={materials.Colors}
              position={[-109, 144.349, -71]}
            />
            <mesh
              geometry={nodes.Handle1_Colors_0.geometry}
              material={materials.Colors}
              position={[-102, 137.5, -97.5]}
            />
            <mesh
              geometry={nodes.Handle2_Colors_0.geometry}
              material={materials.Colors}
              position={[-102, 137.5, -112.5]}
            />
            <mesh
              geometry={nodes.Handle3_Colors_0.geometry}
              material={materials.Colors}
              position={[-102, 65, -105]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.Fridge_Colors_0.geometry}
              material={materials.Colors}
              position={[-145, 100, -105]}
            />
            <mesh
              geometry={nodes.Carpet_Colors_0.geometry}
              material={materials.Colors}
              position={[28.05, 1, 12.847]}
              scale={[1.35, 0.025, 0.9]}
            />
            <mesh
              geometry={nodes.Picture_Colors_0.geometry}
              material={materials.Colors}
              position={[-172.5, 140, 127.5]}
              scale={[1, 1.5, 1.5]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/gym.glb");
